import Head from 'next/head'
import Header from '../components/Header'
import Items from '../components/Items'
import { products } from '../data'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Tesla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/> 
      {products.map(product => (
        <Items
          key = {product.id}
          title = {product.title}
          description = {product.description}
          backgroundImg = {product.backgroundImg}
          leftButtonText = {product.leftButtonText}
          rightButtonText = {product.rightButtonText}
          twoButtons = {product.twoButtons}
          first = {product.first}
        />
      ))}
      
 
    </div>
  )
}
